### ISSUE TITLE
How to relate the length of a list and its shape?

### ISSUE THREAD

**Issue by SolalPirelli** [verifast/verifast#133]
Example:

```
int main()
//@ requires true;
//@ ensures true;
{
  int arr[3];
  //@ assert ints(arr, 3, ?lst);
  //@ assert length(lst) == 3;
  //@ assert lst == cons(?a, cons(?b, cons(?c, nil)));

  return 0;
}
```

With both redux and Z3v4.5, output is `test.c(8,39-43): Cannot prove value4 == nil`, i.e. VeriFast cannot infer the shape of the list from its length.

Is there any existing lemma or other trick I could use to automatically derive a list's shape from its length?

**Comment by btj** [comment]
This works:
```c
/*@

lemma void isnil<t>(list<t> xs)
    requires switch (xs) { case nil: return true; case cons(h, t): return false; };
    ensures true;
{}

@*/

int main()
//@ requires true;
//@ ensures true;
{
  int arr[3];
  //@ assert ints(arr, 3, ?lst);
  //@ assert length(lst) == 3;
  //@ assert lst == cons(?a, cons(?b, cons(?c, ?nil_)));
  //@ isnil(nil_);
  //@ assert nil_ == nil;

  return 0;
}
```

`assert x == ctor(ARGS)` performs a case analysis to check that the non-`ctor` cases are infeasible, but only if one of `ARGS` is a pattern. Since `nil` takes no arguments, this implicit case analysis cannot be triggered for `nil` in this way, so unfortunately an explicit case analysis is necessary for now.

**Comment by SolalPirelli** [comment]
Thanks! For some reason I never thought of using `switch` as a boolean expression in a requires clause.
