### ISSUE TITLE
Relocation R_X86_64_32 against `.rodata.str1.1' can not be used

### ISSUE THREAD

**Issue by BLepers** [verifast/verifast#145]
When I make the project in src/ I get the following error:
```
/usr/bin/x86_64-linux-gnu-ld: /tmp/vfdeps/lib/ocaml/libasmrun.a(startup_aux.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
```

This is fixed by changing the src/GNUmakefile as follows:
```
-OCAMLCFLAGS += -g -w p
+OCAMLCFLAGS += -g -w p -fPIC -runtime-variant _pic
```

**Comment by btj** [comment]
I get the same error on Ubuntu 18.04. This probably has to do with the fact that Ubuntu has [enabled PIE by default](https://wiki.ubuntu.com/SecurityTeam/PIE) since version 16.10. My `vfdeps` package, however, was built on Ubuntu 14.04 LTS, so the OCaml runtime library `libasmrun.a` included in that package was compiled as position-dependent code. (OTOH, in that case it's strange that the compiler flags you propose fix the problem.)
