### ISSUE TITLE
Exception failure when defining SIZE_MAX macro and include stdint.h

### ISSUE THREAD

**Issue by necto** [verifast/verifast#151]
This happened to me in a multi-file project, where the essence of the problem was not obvious. verifast(750e47ffa0c2787dcc88beb59fa87347e5479b01) crashes with:
> Fatal error: exception Failure("hd")

Only when I minimized the failing example, I found out that the issue was in redefining one of the standard macros.

```C
#include <stdint.h>
#define SIZE_MAX 65535
#include <stdint.h>

void foo()
/*@ requires true; @*/
/*@ ensures true; @*/
{
  SIZE_MAX;
}
```
It would be more helpful, if the tool could at least mention the name of the macro redefined, or produce a more detailed error report.

**Comment by btj** [comment]
The crash happened while VeriFast was reporting a divergence between the standard preprocessor and the context-free preprocessor at the point of the call of `SIZE_MAX` in `foo`. The divergence is due to the fact that the standard preprocessor's definition of `SIZE_MAX` at that point is `65535` and the context-free one's is `UINTPTR_MAX` (which is a keyword in VeriFast and therefore a different token, even if you are running with `-target IP16`). The context-free one's is `UINTPTR_MAX` because at a secondary inclusion of a header file that has already been included before, the context-free preprocessor re-defines all macros that were defined by the earlier inclusion, to the same values. This is the right thing to do if the secondary inclusion is in a different file from the first inclusion; it is not really the right thing to do if the secondary inclusion is in the same file, but this scenario seems so uncommon that I am not bothering to write code for that case at this point (but I am open to input on that).

VeriFast used to assume that this kind of divergence could only happen due to a header being included under a context of macro definitions that influenced the header's expansion. This fix makes VeriFast not crash if that is not the case, but note that the error message still refers to that scenario, which is not what is happening here, but again I am not bothering to fix that at this point.
