### ISSUE TITLE
"Parse error: Macro parameter expected" with variadic macros

### ISSUE THREAD

**Issue by DestyNova** [verifast/verifast#244]
I tried verifying a trivial Linux kernel module with verifast and ran into an error parsing a macro:

```
$ make verify_verifast
~/code/verification/verifast/build/verifast-21.04-18-g36fb5486/bin/verifast \
        -I /lib/modules/5.11.0-31-generic/build/include \
        -I /usr/src/linux-headers-5.11.0-31-generic/arch/x86/include \
        -I /usr/src/linux-headers-5.11.0-31-generic/arch/x86/include/generated \
        -D CONFIG_PREEMPT_RT=0 \
        -D MODULE \
        -D __KERNEL__ \
        rickroll.c
rickroll.c
/lib/modules/5.11.0-31-generic/build/include/linux/kconfig.h(16,43-46): Parse error: Macro parameter expected
make: *** [Makefile:22: verify_verifast] Error 1
```

The line in question within `kconfig.h` seems to be this:

```c
#define __take_second_arg(__ignored, val, ...) val
```

I'm not a C expert, but I think this is a [variadic macro](https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html). Do you think it would be difficult to support these? In the meantime, maybe I can make a copy of `kconfig.h` that just contains the bare minimum definitions needed to compile my module, although I have a feeling that there will be a ton of errors after this point, since the kernel tree is just... gigantic.

**Comment by btj** [comment]
Variadic macros are indeed not yet supported. It would probably not be much work, but it would not really solve your problem, I think, because there will probably be other parse errors or otherwise unsupported features in these header files.

It usually works better to create your own versions of the header files included by your target module from scratch, and to fill them out as you go. If you then still need variadic macros support, do ping this issue.

Note, by the way, that there is a verified Linux kernel module in `examples/usbkbd`. See [here](https://www.willemp.be/cw/usbkbd/) for more info.

**Comment by DestyNova** [comment]
Thanks @btj -- I'll take a look at that example, sounds helpful.
