### ISSUE TITLE
Array subscripting bypasses overflow check with int* type

### ISSUE THREAD

**Issue by dc-mak** [verifast/verifast#259]
Changing the getchars example in https://github.com/verifast/verifast/blob/fe877962288c27c3ed487bf8781ffac9699f87c9/tutorial_solutions/tuerk.c to use integers instead produces the below

```c
int getint();
    //@ requires true;
    //@ ensures true;
void putint(int c);
    //@ requires true;
    //@ ensures true;

/*@
predicate integers(int *start, int count) =
    count <= 0 ? true : integer(start, _) &*& integers(start + 1, count - 1);
@*/

int *malloc(int count);
    //@ requires true;
    //@ ensures integers(result, count);

void getints(int *start, int count)
    //@ requires integers(start, count);
    //@ ensures integers(start, count);
{
    int i = 0;
    while (i < count)
        //@ requires integers(start + i, count - i);
        //@ ensures integers(start + old_i, count - old_i);
    {
        //@ open integers(start + i, count - i);
        int c = getint();
        *(start + i) = c;
        i++;
        //@ recursive_call();
        //@ close integers(start + old_i, count - old_i);
    }
}
```

which in verifast-21.04-33-g3fc9153e doesn't verify `Potential arithmetic underflow. (Cannot prove 0 <= (start + (sizeof_int * i)).)` This is surprising by itself, I would not have expected a change in the type of thing pointed to should make a difference.

However, changing `*(start + i)` to `start[i]` allows the example to pass. As far as I understand, E1[E2] should be defined/interpreted the same as *((E1) + (E2)), hence my surprise at the difference in behaviour.

**Comment by btj** [comment]
Indeed, VeriFast symbolically evaluates `*(start + i)` and `start[i]` differently. `*(start + i)` is symbolically evaluated just like any other dereference of a pointer to `int`, whereas evaluation of `start[i]` first looks for an `ints(start, ?n, ?vs)` chunk where `i <= n` and, if it finds one, returns `nth(i, vs)`. This is convenient for "random access" to `ints`-encoded arrays. If it does not find such a chunk, it falls back to looking for an `integer(start + i, _)` chunk, but the `start + i` computation is indeed not checked for overflow. This seems sound because if the `integer` chunk exists, it implies that the address is within the limits.

**Comment by btj** [comment]
You can make your code go through by inserting `integer_limits(start + i);`. It calls a lemma defined in `prelude.h`.

**Comment by dc-mak** [comment]
Thanks for the prompt clarification! I think I was doing something wrong/extra, since I can't seem to reproduce/retrace the steps I took to get the behaviour to be different for the different types.
