### ISSUE TITLE
How to convert `struct symbol_t[]` to a `pointer`

### ISSUE THREAD

**Issue by eleehiga** [verifast/verifast#282]
In https://github.com/clamiax/snore/blob/master/snore.c `symbols` is defined as 
```
static Symbol symbols[] = {
	/* symbol  multiplier  precision */
	{ 's',     1,          3 }, /* first is default (if no suffix) */
	{ 'm',     60,         0 },
	{ 'h',     3600,       0 },
	{ 'd',     86400,      0 }, /* last is default (if no arguments) */
};
```
for the line `if(s[0] == symbols[j].sym) { ` there is the error message: `No matching heap chunks: [_]symbol_t_sym((symbols + (struct_symbol_t_size * j2)), _)`.  Therefore I made a lemma here deal with that: 
```
lemma void indexing_sym(int j);
	requires symbol_t_sym(symbols, _);
	ensures symbol_t_sym(symbols + sizeof(symbols) * j, _);
```
However this has the error message: `Operand of addition or subtraction must be pointer, integer, char, short, or real number: t1 struct symbol_t[4] t2 int32`. This stumped me as in the first error message `symbols` is a `pointer` but in the second error it is a `struct symbol_t[]`. Therefore I was wondering if you guys have a way I can convert symbols from a  `struct symbol_t[]` to a `pointer`?

**Comment by jpdoyle** [comment]
To use a global array, you'll need to `require` a heap chunk for it. Because it's an array of structs, verifast's default points-to notation doesn't currently support it. So you need to define a predicate representing the array. A first step is something like:
```c
typedef struct symbol_t {
	char sym;
	int mult;
	int precision;
} Symbol;

#define SYMBOLS_LEN 4

static Symbol symbols[] = {
	/* symbol  multiplier  precision */
	{ 's',     1,          3 }, /* first is default (if no suffix) */
	{ 'm',     60,         0 },
	{ 'h',     3600,       0 },
	{ 'd',     86400,      0 }, /* last is default (if no arguments) */
};

/*@

inductive isymbol = isymbol(char,int,int);

predicate Symbol_array(Symbol* arr, int len; list<isymbol> symbols) =
    len == 0 ? symbols == {}
    :   len > 0
    &*& arr[0].sym |-> ?symbol
    &*& arr[0].mult |-> ?mult
    &*& arr[0].precision |-> ?prec
    &*& struct_symbol_t_padding(arr)
    &*& Symbol_array(arr+1,len-1,?rest)
    &*& symbols == cons(isymbol(symbol,mult,prec),rest)
    ;

  @*/

void check_symbols()
    /*@ requires [_]Symbol_array(symbols,SYMBOLS_LEN,?symbs); @*/
    /*@ ensures true; @*/
{
    int x = symbols[0].precision;
    /*@ assert x == 3; @*/
}
```
However, you'll need to also add assumptions about the actual _value_ of `symbols` to get this to verify, because nothing prevents `symbols` from being modified!

To initially generate the `Symbols_array` heap chunk, you'll need to use `open_module` to initialize it at the start of `main()`. https://github.com/verifast/verifast/commit/c22f06a1ac9dd753f13b2ded038ecd9170db04ea has a description of the `open_module` feature, and there are several examples of usage in `examples/`, e.g. https://github.com/verifast/verifast/blob/master/examples/globals.c

**Comment by eleehiga** [comment]
@jpdoyle Thank you very much for this and the first step to making such a predicate. But I was wondering if you could please give me a hint about how I can add assumptions about `symbols`. This is as I am trying something like (I know this is wrong):
```
lemma int prec_assertion(Symbol* arr, int i)
	requires [_]symbol_t_precision(arr + sizeof(arr)/8 * i,?prec0);
	ensures prec0 == result;
{
	return arr[i].precision;
}

void check_symbols()
    /*@ requires [_]Symbol_array(symbols,SYMBOLS_LEN,?symbs); @*/
    /*@ ensures true; @*/
{
    int x = symbols[0].precision;
	//@ prec_assertion(symbols, 0);
    /*@ assert x == 3; @*/
}
```

**Comment by jpdoyle** [comment]
if you have `[_]symbol_t_precision(arr + sizeof(symbol_t) * i, ?prec0)`, I think after running `int x = arr[i].precision;`, you will know that `prec0 == x` (note that I used `i` instead of `0`).

The problem with doing `arr[0].precision` is that it isn't a pure value, it's a pointer dereference. Pointer dereferences can't happen in predicates, but you can instead do something like:
```
ensures [_]arr[i].precision |-> ?v &*& prec0 == v;
```
I read this as "I have shared access to `arr[i].precision`, which is allocated and has value `v`, and separately `prec0 == v`".

I'm pretty sure `[_]arr[i].precision |-> ?v` is just syntactic sugar for `[_]symbol_t_precision(arr + sizeof(symbol_t)*i, ?v)`, though.

The way to add assumptions about "symbols" is to state things about the pure value `symbs`. You can do that by adding more assertions, or by replacing `?symbs` with a specific value. For example:
```
// replacing ?symbs
requires [_]Symbol_array(symbols,2,{isymbol('a',1,1),isymbol('b',2,2)});
// adding more assertions

requires [_]Symbol_array(symbols,2,?symbs) &*& symbs == {isymbol('a',1,1),isymbol('b',2,2)};
```
would both require that `symbols` has the values you'd see if the array got initialized with `{ { 'a', 1, 1 }, { 'b', 2, 2 } }` instead.

**Comment by eleehiga** [comment]
@jpdoyle Thank you very much. The following did not work:
```
lemma int prec_assertion(Symbol* arr, int i);
	requires [_]symbol_t_precision(arr + sizeof(arr)/8 * i, ?prec0);
	ensures [_]arr[i].precision |-> ?v &*& prec0 == v;
```
But what you said with the following worked:
```
void check_symbols()
    /*@ requires [_]Symbol_array(symbols,SYMBOLS_LEN,?symbs) &*& symbs == {isymbol('s',1,3 ),isymbol('m',60,0),isymbol('h',3600,0),isymbol('d',86400,0)}; @*/
    /*@ ensures true; @*/
{
    int x = symbols[0].precision;
    /*@ assert x == 3; @*/
    char y = symbols[1].sym;
    /*@ assert y == 'm'; @*/
    int z = symbols[2].mult;
    /*@ assert z == 3600; @*/
}
```
Thank you again and now I will take some more time to understand this and then move on to `Symbols_array` heap chunk in main.

**Comment by eleehiga** [comment]
@btj Thank you very much for implementing that change
