### ISSUE TITLE
Modular Arithmetic and Unsigned Integers

### ISSUE THREAD

**Issue by rsaill** [verifast/verifast#305]
If remark that, with the following function
```
void foo(uint32_t x){
  uint16_t y = (uin16_t) x;
} 
```
Verifast tries to check that x is smaller than UINT16_MAX.

I far as I know, even if x is greater, this is perfectly valid C code and the value for y should be x modulo  2^16.

Can Verifast deal with this code (without completely deactivating the overflow checks)?

**Comment by jpdoyle** [comment]
Verifast has a `truncating` keyword that you can use to explicitly allow unsigned overflow, see https://github.com/verifast/verifast/blob/master/examples/truncating.c

Depending on what you need to prove, you may need to add a few axioms about how that truncation works, since the VeriFast definitions for `truncate_unsigned` are rather limited: https://github.com/verifast/verifast/blob/5d6271c82a82aff7536db91576e5f673ebf06182/bin/bitops.gh#L88

**Comment by btj** [comment]
No extra axioms should be necessary; `truncate_unsigned_def` fully defines the result?
