### ISSUE TITLE
Proving that a pointer is not null

### ISSUE THREAD

**Issue by rsaill** [verifast/verifast#312]
I am able to prove the following lemma for integer pointers
```
lemma void not_null(int *p)
  requires *p |-> _;
  ensures *p |-> _ &*& p != NULL;
{
  integer_limits(p);
}
```

How can I prove the same lemma for other types of pointers?
For instance, I would like to prove the following lemma
```
struct Int {
  int val;
};
lemma void not_null_2(struct Int *p)
  requires *p |-> _;
  ensures *p |-> _ &*& p != NULL;
{

}
```
In the same vein, I would like to prove
```
lemma void not_null_3(struct Int *p)
  requires p->val |-> _;
  ensures p->val |-> _ &*& p != NULL;
{
}
```
Is that even possible?

**Comment by btj** [comment]
You can open the Int_val(p, _) chunk to get the integer(p, val) chunk and then apply integer_limits.

Note that this only works for the first field of a struct. Otherwise, you could unsoundly prove that there is no int at address 1000000 by declaring a struct Foo { char dummy[1000000]; int val; } and then, from any integer(p, _) deriving Foo_val((void*)p - 1000000, _) simply by closing it.

**Comment by rsaill** [comment]
Ok, so I can prove `not_null_3` but only when val is the first field of the struct otherwise it would make Verifast inconsistent.

But what about `not_null_2` then? Is there a similar problem?

**Comment by btj** [comment]
`not_null_2` uses a points-to assertion for an object of struct type. That's not really supported yet. (I was actually surprised that VeriFast accepted it at all.) Instead, use points-to assertions for each field separately, as in `not_null_3`.

**Comment by rsaill** [comment]
Ok, thanks.
