### ISSUE TITLE
SMT solver incompleteness due to trigger premise checking

### ISSUE THREAD

**Issue by necto** [verifast/verifast#49]
Here is a working piece of code:

```OCaml
/*@
predicate my_predicate(int data);

lemma void produce_pred1(list<int> ddd);
requires true;
ensures my_predicate(nth(0, update(0, 2, ddd)));
@*/

void to_verify()
/*@ requires true; @*/ 
/*@ ensures true; @*/
{
//@ list<int> dd;
// // // produce_pred1(dd);  <-- note this line is commented out
//@ assume(length(dd) > 0);
//@ assert(nth(0, update(0, 2, dd)) == 2);
}
```

However, the moment I uncomment the call to the `produce_pred1` lemma:

```OCaml
//@ produce_pred1(dd);
```
VeriFast fails to prove the assertion. so presence of the `my_predicate(nth(n, update(0, 2, dd)))` in the heap prevents it from proving the basic equality.

How can I prevent this?

**Comment by btj** [comment]
The failure to prove the assertion is not due to the presence of the chunk in the heap: you get the same failure if you replace the lemma call by the line
```
//@ { int x = nth(0, update(0, 2, dd)); }
```
The failure is due to the incompleteness of the SMT solvers. (The failure occurs both when using Z3 and when using Redux.)

In the original program, the SMT solver succeeds in proving the assertion thanks to the `nth_update` autolemma declared in `list.gh`. (You can verify this by commenting out that declaration.) VeriFast passes this autolemma to the SMT solver as a universally quantified axiom at the point where it processes the autolemma declaration.

However, SMT solvers are incomplete for theories involving universal quantification. They try to instantiate the quantified axioms appropriately, using heuristics, but they may miss some relevant instantiations.

The most commonly used heuristic, and the one used by Redux (and probably by Z3), is triggering. In this approach, one or more triggers are associated with each universally quantified axiom. A trigger is a term pattern. Every time a term that matches this pattern is constructed, the quantifier is instantiated for that term. Notice that the `nth_update` autolemma declares the trigger `nth(i, update(j, y, xs))`. This means that Redux will instantiate the axiom whenever a term of the form `nth(_, update(_, _, _))` is constructed.

In the original program, this does the job. However, in the modified program, the term `nth(0, update(0, 2, dd))` is constructed when the `produce_pred1` lemma call is processed. At that point, the precondition for the autolemma (which is the premise for the axiom) cannot be proved, since the `length(dd) > 0` assumption has not yet been made. In Redux, if an axiom's premise does not hold at the point of triggering, that instantiation is not retried again later. This causes the failure. In seems that Z3 (at least the old version 1.3.6 used by VeriFast) has similar behavior.

There are at least two workarounds for this incompleteness:
- Move the `assume` statement above the `produce_pred1` lemma call
- Call the `nth_update` lemma explicitly after the lemma call:
  ```
  //@ nth_update(0, 0, 2, dd);
  ```

Another solution would be to modify Redux so that, instead of checking an axiom's premise at triggering time, it remembers the implication `premise ==> conclusion`, and it re-tries proving the premise whenever new information becomes available. However, the latter approach has a significant performance impact: I know this because I introduced the premise checking behavior for performance reasons. Therefore, I am disinclined to make this change.

I changed the title of this issue to accurately reflect the problem, and I'm closing it as 'won't fix'. Feel free to reopen if you disagree.
