### ISSUE TITLE
Error message: `Expressions of type 'uint32_t' are not yet supported as arguments for a varargs function`

### ISSUE THREAD

**Issue by thanhtoantnt** [verifast/verifast#516]
Similar to #284, I want to verify a `printf` statement of a `uint32_t` variable but got this error message: `Expressions of type 'uint32_t' are not yet supported as arguments for a varargs function`. 

So I wonder whether VeriFast can be updated to support this case.
Thanks.

**Comment by btj** [comment]
Could you please post the complete `printf` call that you would like VeriFast to support? In particular: what format specifier would you use with this argument? The C standard does not appear to support `uint32_t` as a `printf` argument type.

I guess the way to go is to add support for `%ld` and the `unsigned long` argument type. `unsigned long` is guaranteed by the standard to be at least as wide as `uint32_t`.

**Comment by thanhtoantnt** [comment]
My simple example:
```
    uint32_t var = 122;
    printf("var = 0x%x\n", var);
```

**Comment by btj** [comment]
This now verifies if you specify a target where `sizeof(unsigned int) == 4`, i.e. target `32bit`, `llp64`, or `lp64` (but not `ip16` or `i16`). It also still fails, as it should, when you don't specify a target, because then VeriFast is in targetless mode, which is meant to be sound with respect to all supported targets (i.e. all of the above).

**Comment by thanhtoantnt** [comment]
Thank you so much.
