### ISSUE TITLE
Redux crashes when a term like 'default_value' is used at different types

### ISSUE THREAD

**Issue by necto** [verifast/verifast#68]
The following code, on the fresh VeriFast build:

```ML
/*@
  lemma void in_nth_bucket(list<list<int > > buckets, int n, int k)
  requires 0 <= n &*& n < length(buckets) &*& true == mem(k, nth(n, buckets));
  ensures true;
  {
    switch(buckets) {
      case nil:
        assume(false);
      case cons(bh,bt):
        assume(false);
    }
  }
  @*/
```

fails with:
> Fatal error: exception File "redux.ml", line 345, characters 73-79: Assertion failed

What does it mean? What may be wrong here?

**Comment by btj** [comment]
Smaller repro:
```c
/*@
  lemma void in_nth_bucket(list<list<int > > buckets, int n, int k)
  requires true == mem(k, nth(n, buckets));
  ensures true;
  {
    assume(buckets == nil);
    assume(false);
  }
  @*/
```
Investigation using `verifast -verbose 1000 test.c`shows that this is the same problem encountered in #34: Redux gets confused when `default_value` is used both as an `int` and as a value of an inductive type (`list<int>` in this case). (It is used as an `int` in autolemma `default_value_eq_zero` in `prelude_core.gh`.) In contrast to the use case described in #34, the use case you show here is entirely legitimate; I am now convinced that this is a serious bug.

It seems that for the time being, a good workaround is to turn autolemma `default_value_eq_zero` in `prelude_core.gh` into a plain lemma. This stops the above programs from crashing.

That workaround is not a panacea, though. It causes Redux to crash in test case `examples/io/in-memory/writer_cat_reader/main.c`. And interestingly, here it does not crash at the same line. Here, the problem seems to be that `default_value` is used as a value of two distinct inductive types, with a different number of constructors. So even the usual boxing and unboxing (which only deals with differences in prover_types, such as `int` versus `inductive`) would not seem to solve this problem. It seems we might need full-blown "run-time type information" (i.e. a reification of VeriFast types as SMT solver terms).

To be investigated further...

**Comment by btj** [comment]
Another approach might be to simply make Redux more robust against type confusions...

**Comment by let-def** [comment]
`read_line` code from the last example of the tutorial triggers the same assertion failure:

```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
char *read_line()
//@requires true;
//@ensures string(result, _) &*& malloc_block_chars(result, _);
{
  char buffer[100];
  int scanf_result = scanf(" %99[^\n]", buffer);
  if (scanf_result < 1) abort();
  char *result = strdup(buffer);
  if (result == 0) abort();
  return result;
}
```

(and turning `default_value_eq_zero` into plain lemma fixes it).

**Comment by btj** [comment]
Thanks for reporting!

My current plan is to implement type reification in the near future; it also fixes some other problems. However, it's a pretty big job, so it might be a while before I have time for it.
