### ISSUE TITLE
Predicate Values and Function Pointers

### ISSUE THREAD

**Issue by JoergPfaehler** [verifast/verifast#75]
Im am currently trying to verify the following (simplified example):

```
typedef void fun_t/*@(predicate(void*) validstate)@*/(void* state);
  //@requires validstate(state);
  //@ensures validstate(state);

struct interface_t {
  fun_t* f;
};

/*@
  predicate valid_interface(struct interface_t* i, predicate(void*) validstate) =
    interface_t_f(i, ?f) &*& is_fun_t(validstate)(f) == true;
@*/
```

The idea is to separate interface and implementation (the latter is not shown). The interface is described by the above structure where each of the methods has an additional parameter for the state of an implementation. The state has some invariant described by the validstate-predicate. I would like to express that a client has a handle to a valid interface structure, which basically means that each function pointer satisfies the contract for a given validstate predicate. Is this the correct syntax for this? Is there a better way to achieve this (that is currently supported)? Currently VeriFast yields an error "Expression form not allowed here." for _is_fun_t(...)(...)_ in the example.

**Comment by btj** [comment]
Try `is_fun_t(f, validstate)` (without the `== true`). Otherwise, yes; at least, this is the way I do it as well (except that it gets a bit trickier if you want to pass the "object" as an argument to the "method"). (See e.g. `examples/termination/funcptr.c`. Note: this example also proves termination; you can ignore the `call_perm` business if you only care about partial correctness.)

**Comment by JoergPfaehler** [comment]
That works fine, thanks!
